### ISSUE TITLE
Failed to instatiate template file compare.v3s.

### ISSUE THREAD

**Issue by mice-exp** [qualisys/paf-theia-markerless-example#2]
Hello, 
I've tried opening the PAF Theia markerless example. Though when I start processing the example data, I get the following message : 
![errortheia](https://user-images.githubusercontent.com/72578459/202424282-6a5c39ba-2fee-4209-8e82-724c4406d563.PNG)
And I'm not being able to export the data to Theia 3D.

Could you please tell me what could be the cause of this error?
Thank you!

**Comment by DocVi** [comment]
Hi,

Thank you for your feedback.
Could you try to rename your project "Universite" instead of "Université". Just checking if the special character "é" is the cause the problem?
Keep me posted.

Thanks

**Comment by mice-exp** [comment]
> 

Hello, 
Thank you for this observation. Indeed the special character was the issue. All is working well now. 
Thank you for your time and help!

**Comment by DocVi** [comment]
Glad to hear.
We will support the special characters in a future version
