### ISSUE TITLE
Issue Merging Analog with Theia Files

### ISSUE THREAD

**Issue by MatthewRauseoTMC** [qualisys/paf-theia-markerless-example#7]
Hello,

Having a bit of an issue getting markerless data and analog data to merge correctly in V3D while using this PAF. I have modified the PAF so that the file names identify the movement completed in the trial (see file "SettingsEx.txt"). I modified the "create_workspace" template as recommended by the support team so that the /OTHER3D_FILE_MASK command was set to *.c3d (see file create_workspace). However, when the data is sent to V3D, I can't merge the analog data with the motion capture data correctly. If processed as a batch, all of the analog data from only the first collected trial is merged with every motion capture trial and I receive a message stating that the files are duplicates and I can either append each trial or skip the duplicate files (see attached Screenshot). If files are processed independently they still merge with only the first trial of data collected (see attached video). Just wondering if you had an recommendations to get this PAF to merge multiple different analog files and motion trials correctly.

Thank you for your time and any feedback you can provide!

[SettingsEx.txt](https://github.com/qualisys/paf-theia-markerless-example/files/13833955/SettingsEx.txt)
[create_workspaceEx.txt](https://github.com/qualisys/paf-theia-markerless-example/files/13833978/create_workspaceEx.txt)
![DuplicateScreenshot](https://github.com/qualisys/paf-theia-markerless-example/assets/155668444/996c0fc3-9130-4bbc-8253-3bf117664170)
https://github.com/qualisys/paf-theia-markerless-example/assets/155668444/2cfe33a0-32f6-44c0-8df8-84b6bdd798dc

**Comment by LiborSoumar** [comment]
@MatthewRauseoTMC Hi Mattew, I tried your Settings.paf and create_workspace.v3s with some of my CMJ data and merge works fine. I assume problem is related to your specific data. Will you be willing to share your data so that I can replicate your problem?

**Comment by LiborSoumar** [comment]
@MatthewRauseoTMC Hi Matthew, we have not heard from you. We will close this issue. If you still need any help, please contact our support.
